name: publish
run-name: ${{ github.actor }} is publishing design-system-web
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: All Steps (Build, Test & Deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"

      # versioning
      - name: Apply version desing-system-web-lib
        run: npm version minor -m "Upgrade to..."
        # run: cd libs/design-system-web-lib && npm version minor -m "Upgrade to..." && cd ../..
      - name: Git push version bump
        run: git push && git push --tags
      - id: set-version
        name: Output version change
        run: npm pkg get version

      - name: Install dependencies
        run: npm install

      # desing-system-web-lib
      - name: Building desing-system-web-lib
        run: npx nx run design-system-web-lib:build --configuration=production
      - name: Linting desing-system-web-lib
        run: npx nx run design-system-web-lib:lint
      - name: Unit testing desingn-system-web-lib
        run: npx nx run design-system-web-lib:test

      # Storybook
      - name: Building Storybook desing-system-web-lib
        run: npx nx run design-system-web-lib:build-storybook
      # - name: Testing Storybook desingn-system-web-lib
      #   run: npx nx run design-system-web-lib:test-storybook       
     
      # Npm Pack      
      # - name: Packing 
      #   run: npm pack -w:dist/libs/design-system-web-lib --pack-destination dist/libs/design-system-web-lib

      - name: Publishing npmjs.com package
        run: npm publish dist/libs/design-system-web-lib --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: nx publishing 
      #   run: npx nx run design-system-web-lib:nx-release-publish --packageRoot=dist/libs/design-system-web-lib

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false