name: publish
run-name: ${{ github.actor }} is publishing design-system-web
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    name: All Steps (Build, Test & Deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Set git configuration
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Setup .npmrc file to publish to npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore/create node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # versioning
      - name: Apply project version
        run: yarn version --patch
      
      - name: Apply lib css version
        run: yarn version --new-version `echo $(npm pkg get version) | sed -e 's/\"//g'` --cwd libs/css --no-git-tag-version

      - name: Apply lib icons version
        run: yarn version --new-version `echo $(npm pkg get version) | sed -e 's/\"//g'` --cwd libs/icons --no-git-tag-version

      - name: Apply lib assets version
        run: yarn version --new-version `echo $(npm pkg get version) | sed -e 's/\"//g'` --cwd libs/assets --no-git-tag-version

      - name: Apply lib angular version
        run: yarn version --new-version `echo $(npm pkg get version) | sed -e 's/\"//g'` --cwd libs/angular --no-git-tag-version

      - name: Apply lib css version
        run: yarn version --new-version `echo $(npm pkg get version) | sed -e 's/\"//g'` --cwd libs/css --no-git-tag-version

      - name: Git push version
        run: git push && git push --tags

      - name: Install dependencies
        run: yarn install --silent --frozen-lockfile

      - name: Building
        run: yarn build

      - name: Linting
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Unit testing
        run: yarn test

      # Storybook
      # - name: Building Storybook
      #   run: yarn build-storybook
      # - name: Testing Storybook desingn-system-web-lib
      #   run: npx nx run design-system-web-lib:test-storybook
      # yarn playwright install

      # Npm Pack
      # - name: Packing
      #   run: npm pack -w:dist/libs/design-system-web-lib --pack-destination dist/libs/design-system-web-lib

      - name: Publishing npmjs.com => css
        run: yarn publish dist/libs/css --access public --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing npmjs.com => icons
        run: yarn publish dist/libs/icons --access public --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing npmjs.com => assets
        run: yarn publish dist/libs/assets --access public --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # TODO: descomentar
      # - name: Publishing npmjs.com => angular
      #   run: yarn publish dist/libs/angular --access public --no-git-tag-version
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}




      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
